(define-module (gaia server)
  #:use-module (ice-9 match)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 regex)
  #:use-module (srfi srfi-13)
  #:use-module (srfi srfi-1)
  #:use-module (ice-9 rdelim)
  #:use-module (gaia core)
  #:use-module (gaia rlm-env)
  #:use-module (gaia config)
  #:use-module (gaia llm-client)
  #:use-module (gaia utils)
  #:use-module (fibers)
  #:use-module (fibers channels)
  #:use-module (goblins)
  #:use-module (gaia actors)
  #:export (start-server replay-history parse-slash-command handle-client)
  #:re-export (save-session load-session))



(define (replay-history env history)
  "Re-executes all code blocks found in the history to restore REPL state."
  (let ((history-list (if (vector? history) (vector->list history) history)))
    (for-each (lambda (turn)
                (let ((role (or (assoc-ref turn 'role) (assoc-ref turn "role")))
                      (trajectory (or (assoc-ref turn 'trajectory) (assoc-ref turn "trajectory"))))
                  (if trajectory
                      (for-each (lambda (step)
                                  (let ((step-role (or (assoc-ref step 'role) (assoc-ref step "role")))
                                        (step-content (or (assoc-ref step 'content) (assoc-ref step "content"))))
                                    (when (and step-role (string=? (format #f "~a" step-role) "assistant") step-content)
                                      (let ((code (or (extract-code step-content)
                                                      (if (or (string-prefix? "(" step-content)
                                                              (string-prefix? ";" step-content))
                                                          step-content #f))))
                                        (when code
                                          (rlm-eval! env code #:permission-handler (lambda (_) #t)))))))
                                (if (vector? trajectory) (vector->list trajectory) trajectory))
                      (let ((content (or (assoc-ref turn 'content) (assoc-ref turn "content"))))
                        (when (and role content)
                          (let ((role-str (format #f "~a" role)))
                            (cond
                             ((string=? role-str "assistant")
                              (let ((code (or (extract-code content)
                                              (if (or (string-prefix? "(" content)
                                                      (string-prefix? ";" content))
                                                  content #f))))
                                (when code
                                  (rlm-eval! env code #:permission-handler (lambda (_) #t)))))
                             ((string=? role-str "user-repl")
                              (let ((code (extract-code content)))
                                (when code
                                  (rlm-eval! env code #:permission-handler (lambda (_) #t))))))))))))
              history-list)))

(define (set-nonblocking! port)
  (fcntl port F_SETFL (logior O_NONBLOCK (fcntl port F_GETFL)))
  (setvbuf port 'none))

(define (parse-slash-command str)
  "Parses a slash command string and returns the corresponding protocol S-expression or #f."
  (let* ((trimmed (string-trim-both str))
         (parts (string-split trimmed #\space))
         (cmd (car parts))
         (args (string-trim-both (string-join (cdr parts) " "))))
    (cond
     ((string=? cmd "/help")
      '(help))
     ((string=? cmd "/env")
      '(env))
     ((string=? cmd "/clear")
      '(clear))
     ((string=? cmd "/models")
      '(list-models))
     ((string=? cmd "/model")
      (if (string-null? args)
          '(get-model)
          `(set-model ,args)))
     ((string=? cmd "/thinking")
      (if (string-null? args)
          '(get-thinking)
          `(set-thinking ,args)))
     ((string=? cmd "/state")
      (if (string-null? args)
          '(get-state-injection)
          `(set-state-injection ,args)))
     ((string=? cmd "/wisp")
      (if (string-null? args)
          '(get-wisp-mode)
          `(set-wisp-mode ,args)))
     ((string=? cmd "/solve")
      (if (string-null? args)
          #f
          `(solve ,args)))
     ((string=? cmd "/ask")
      `(ask ,args))
     ((string=? cmd "/eval")
      (if (string-null? args)
          #f
          `(repl ,args)))
     ((string=? cmd "/session")
      `(session ,args))
     ((string=? cmd "/sessions")
      '(list-sessions))
     ((string=? cmd "/history")
      '(get-history))
     (else
      #f))))

(define (clean-history history)
  "Returns history with assistant content cleaned for display."
  (map (lambda (turn)
         (let ((role (or (assoc-ref turn 'role) (assoc-ref turn "role")))
               (content (or (assoc-ref turn 'content) (assoc-ref turn "content"))))
           (if (and role (string=? (format #f "~a" role) "assistant") content)
               (map (lambda (pair)
                      (if (member (car pair) '("content" content))
                          (cons (car pair) (clean-assistant-content content))
                          pair))
                    turn)
               turn)))
       history))

(define (operation-matches-scopes? expr scopes)
  (any (lambda (scope)
         (match scope
           (('always . approved-expr)
            (equal? expr approved-expr))
           (('directory . dir-prefix)
            (and (eq? (car expr) 'write-file)
                 (string-prefix? dir-prefix (cadr expr))))
           (_ #f)))
       scopes))

(define (handle-client client-socket)
  (set-port-encoding! client-socket "UTF-8")
  (set-nonblocking! client-socket)
  (let ((channel (make-channel))
        (perm-mutex (make-mutex))
        (perm-cond (make-condition-variable))
        (perm-state 'idle)        ;; 'idle, 'pending, 'resolved, 'interrupted, 'eof
        (perm-value #f)
        (approved-scopes '()))
    ;; Spawn the asynchronous socket reader fiber
    (spawn-fiber
     (lambda ()
        (let loop ()
          (let* ((line (catch #t
                         (lambda () (read-line client-socket))
                         (lambda _ (with-input-from-string "" read))))
                 (msg (if (eof-object? line)
                          line
                          (catch #t
                            (lambda () (with-input-from-string line read))
                            (lambda _ 'error)))))
            (cond
             ((eof-object? line)
              (gaia-log "[SERVER] Client connection closed (EOF).")
              (put-message channel 'eof)
              (with-mutex perm-mutex
                (set! perm-state 'eof)
                (signal-condition-variable perm-cond)))
             ((equal? msg '(interrupt))
              (gaia-log "[SERVER] Received (interrupt) from client.")
              ;; Set the global *interrupted* flag in core
              (let ((core-mod (resolve-module '(gaia core) #:ensure #f)))
                (when core-mod
                  (module-set! core-mod '*interrupted* #t)))
              ;; Cancel any active LLM request immediately
              (abort-active-llm-calls!)
              (send-event client-socket '(error "Interrupted"))
              (put-message channel 'interrupt)
              (with-mutex perm-mutex
                (set! perm-state 'interrupted)
                (signal-condition-variable perm-cond))
              (loop))
             ((and (pair? msg) (eq? (car msg) 'permission-response))
              (gaia-log (format #f "[SERVER] Received permission response: ~s" msg))
              (with-mutex perm-mutex
                (let ((res (cadr msg)))
                  (match res
                    (('always approved-expr)
                     (set! approved-scopes (cons (cons 'always approved-expr) approved-scopes))
                     (set! perm-value #t))
                    (('directory dir-path)
                     (set! approved-scopes (cons (cons 'directory dir-path) approved-scopes))
                     (set! perm-value #t))
                    (val
                     (set! perm-value val))))
                (set! perm-state 'resolved)
                (signal-condition-variable perm-cond))
              (loop))
             (else
              (gaia-log (format #f "[SERVER] Received client message: ~s" msg))
              (put-message channel msg)
              (loop)))))))
    (let* ((event-sink (lambda (event) (send-event client-socket event)))
           (permission-sink (lambda (expr)
                              (let ((bypass? #f))
                                (with-mutex perm-mutex
                                  (when (operation-matches-scopes? expr approved-scopes)
                                    (set! bypass? #t)))
                                (if bypass?
                                    (begin
                                      (gaia-log (format #f "[SERVER] Permission request bypassed by scope rules: ~s" expr))
                                      #t)
                                    (begin
                                      (gaia-log (format #f "[SERVER] Prompting client for permission-request: ~s" expr))
                                      (with-mutex perm-mutex
                                        (set! perm-state 'pending))
                                      (send-event client-socket `(permission-request ,expr))
                                      (with-mutex perm-mutex
                                        (let loop ()
                                          (cond
                                           ((eq? perm-state 'resolved)
                                            (let ((val perm-value))
                                              (set! perm-state 'idle)
                                              (gaia-log (format #f "[SERVER] Permission request resolved: ~s -> ~s" expr val))
                                              val))
                                           ((eq? perm-state 'interrupted)
                                            (set! perm-state 'idle)
                                            (gaia-log (format #f "[SERVER] Permission request interrupted: ~s" expr))
                                            (throw 'user-interrupt))
                                           ((eq? perm-state 'eof)
                                            (set! perm-state 'idle)
                                            (gaia-log (format #f "[SERVER] Permission request EOF: ~s" expr))
                                            (throw 'user-interrupt))
                                            (else
                                             (wait-condition-variable perm-cond perm-mutex)
                                             (loop))))))))))
           (first-msg (get-message channel))
           (session-id (match first-msg
                         (('session id) id)
                         (('session id workspace-dir) id)
                         (_ (string-append "gaia-" (number->string (current-time))))))
           (workspace-dir (match first-msg
                            (('session id workspace-dir) workspace-dir)
                            (_ #f)))
           (history (load-session session-id))
           (session-vat (spawn-vat))
           (orchestrator
            (with-vat session-vat
              (let* ((sandbox-actor (spawn ^repl-sandbox session-id event-sink permission-sink history workspace-dir))
                     (llm-client (spawn ^llm-client session-vat))
                     (agent-actor (spawn ^agent-actor session-id sandbox-actor llm-client event-sink permission-sink)))
                (spawn ^session-orchestrator session-id client-socket channel permission-sink sandbox-actor agent-actor llm-client history (get-config 'model) (get-config 'thinking))))))
      (gaia-log (format #f "[SERVER] Session initialized (Goblins Vat): ~a" session-id))
      (with-output-to-file ".last_session" (lambda () (display session-id)))
      (let loop ()
        (let* ((raw-msg (get-message channel))
               (msg (match raw-msg
                      (('eval task)
                       (if (string-prefix? "/" task)
                           (or (parse-slash-command task) raw-msg)
                           raw-msg))
                      (_ raw-msg))))
          (cond
           ((eq? msg 'eof)
            (with-vat session-vat
              (<- orchestrator 'handle-message 'eof))
            (vat-halt! session-vat)
            (close-port client-socket))
           (else
            (with-vat session-vat
              (<- orchestrator 'handle-message msg))
            (unless (eq? msg 'eof)
              (loop)))))))))

(define (start-server path)
  (load-config)
  (gaia-log (format #f "[SERVER] Listening on UNIX socket: ~a" path))
  ;; Ignore SIGPIPE here to avoid hang at top level
  (sigaction SIGPIPE SIG_IGN)
  (with-output-to-file "/tmp/gaia.pid" (lambda () (display (getpid))))
  (when (file-exists? path) (delete-file path))
  (let ((server-socket (socket AF_UNIX SOCK_STREAM 0))
        (addr (make-socket-address AF_UNIX path)))
    (bind server-socket addr)
    (listen server-socket 128)
    (set-nonblocking! server-socket)
    (run-fibers
     (lambda ()
       (let loop ()
         (match (accept server-socket (logior SOCK_NONBLOCK SOCK_CLOEXEC))
           ((client-socket . client-addr)
            (gaia-log "[SERVER] Client connection accepted.")
            (set-nonblocking! client-socket)
            (spawn-fiber (lambda () (handle-client client-socket)))
            (loop)))))
     #:drain? #t)))
