(define-module (gaia server)
  #:use-module (ice-9 match)
  #:use-module (ice-9 threads)
  #:use-module (ice-9 ftw)
  #:use-module (ice-9 regex)
  #:use-module (srfi srfi-13)
  #:use-module (ice-9 rdelim)
  #:use-module (gaia core)
  #:use-module (gaia rlm-env)
  #:use-module (gaia config)
  #:use-module (gaia llm-client)
  #:use-module (gaia utils)
  #:use-module (fibers)
  #:use-module (fibers channels)
  #:export (start-server save-session load-session replay-history))

(define (send-event client-socket event)
  "Write an S-expression event to client, flushing immediately."
  (write event client-socket)
  (newline client-socket)
  (force-output client-socket))

(define (make-broadcast-port out-port event-sink)
  "Creates a soft port that writes to OUT-PORT and also sends strings to EVENT-SINK."
  (make-soft-port
   (vector
    (lambda (c) (write-char c out-port))
    (lambda (s) 
      (display s out-port)
      (let ((trimmed (string-trim-both s)))
        (when (> (string-length trimmed) 0)
          ;; Send debug info but strip ANSI codes for JSON
          (let ((clean (regexp-substitute/global #f "\x1b\\[[0-9;]*m" trimmed 'pre "" 'post)))
            (event-sink `(info ,clean))))))
    (lambda () (force-output out-port))
    #f
    (lambda () #t))
   "w"))

(define (save-session session-id history)
  (unless (file-exists? "sessions")
    (mkdir "sessions"))
  (let ((port (open-file (string-append "sessions/" session-id ".json") "w")))
    (display (scm->json (list->vector history)) port)
    (close-port port)))

(define (load-session session-id)
  (let ((path (string-append "sessions/" session-id ".json")))
    (if (file-exists? path)
        (let* ((port (open-file path "r"))
               (data (read-string port)))
          (close-port port)
          (let ((res (json->scm data)))
            (if (vector? res) (vector->list res) res)))
        '())))

(define (replay-history env history)
  "Re-executes all code blocks found in the assistant's history to restore REPL state."
  (let ((history-list (if (vector? history) (vector->list history) history)))
    (for-each (lambda (turn)
                (let ((role (or (assoc-ref turn 'role) (assoc-ref turn "role")))
                      (content (or (assoc-ref turn 'content) (assoc-ref turn "content"))))
                  (when (and role (string=? (format #f "~a" role) "assistant") content)
                    (let ((code (or (extract-code content)
                                    (if (or (string-prefix? "(" content)
                                            (string-prefix? ";" content))
                                        content #f))))
                      (when code
                        (rlm-eval! env code #:permission-handler (lambda (_) #t)))))))
              history-list)))

(define (set-nonblocking! port)
  (fcntl port F_SETFL (logior O_NONBLOCK (fcntl port F_GETFL)))
  (setvbuf port 'none))

(define (parse-slash-command str)
  "Parses a slash command string and returns the corresponding protocol S-expression or #f."
  (let* ((trimmed (string-trim-both str))
         (parts (string-split trimmed #\space))
         (cmd (car parts))
         (args (string-trim-both (string-join (cdr parts) " "))))
    (cond
     ((string=? cmd "/env")
      '(env))
     ((string=? cmd "/clear")
      '(clear))
     ((string=? cmd "/models")
      '(list-models))
     ((string=? cmd "/model")
      (if (string-null? args)
          '(get-model)
          `(set-model ,args)))
     ((string=? cmd "/thinking")
      (if (string-null? args)
          '(get-thinking)
          `(set-thinking ,args)))
     ((string=? cmd "/ask")
      `(ask ,args))
     ((string=? cmd "/session")
      `(session ,args))
     ((string=? cmd "/sessions")
      '(list-sessions))
     ((string=? cmd "/history")
      '(get-history))
     (else
      #f))))

(define (clean-history history)
  "Returns history with assistant content cleaned for display."
  (map (lambda (turn)
         (let ((role (or (assoc-ref turn 'role) (assoc-ref turn "role")))
               (content (or (assoc-ref turn 'content) (assoc-ref turn "content"))))
           (if (and role (string=? (format #f "~a" role) "assistant") content)
               (map (lambda (pair)
                      (if (member (car pair) '("content" content))
                          (cons (car pair) (clean-assistant-content content))
                          pair))
                    turn)
               turn)))
       history))

(define (handle-client client-socket)
  (set-port-encoding! client-socket "UTF-8")
  (set-nonblocking! client-socket)
  (let ((channel (make-channel)))
    ;; Spawn the asynchronous socket reader fiber
    (spawn-fiber
     (lambda ()
       (let loop ()
         (let* ((line (catch #t
                        (lambda () (read-line client-socket))
                        (lambda _ (with-input-from-string "" read))))
                (msg (if (eof-object? line)
                         line
                         (catch #t
                           (lambda () (with-input-from-string line read))
                           (lambda _ 'error)))))
           (cond
            ((eof-object? line)
             (put-message channel 'eof))
            ((equal? msg '(interrupt))
             ;; Set the global *interrupted* flag in core
             (let ((core-mod (resolve-module '(gaia core) #:ensure #f)))
               (when core-mod
                 (module-set! core-mod '*interrupted* #t)))
             ;; Cancel any active LLM request immediately
             (abort-active-llm-calls!)
             (put-message channel 'interrupt)
             (loop))
            (else
             (put-message channel msg)
             (loop)))))))
    (let* ((event-sink (lambda (event) (send-event client-socket event)))
           (permission-sink (lambda (expr)
                              (send-event client-socket `(permission-request ,expr))
                              (let loop ()
                                (let ((msg (get-message channel)))
                                  (match msg
                                    (('permission-response #t) #t)
                                    (('permission-response #f) #f)
                                    ('interrupt (throw 'user-interrupt))
                                    ('eof (throw 'user-interrupt))
                                    (_ (loop)))))))
           (first-msg (get-message channel))
           (session-id (match first-msg
                         (('session id) id)
                         (_ (string-append "gaia-" (number->string (current-time))))))
           (history (load-session session-id))
           (env (make-rlm-env session-id event-sink permission-sink)))
      (gaia-log (format #f "[SERVER] Session initialized: ~a" session-id))
      (with-output-to-file ".last_session" (lambda () (display session-id)))
      (when (not (null? history))
        (gaia-log (format #f "[SERVER] Replaying ~a turns of history to restore session state." (length history)))
        (replay-history env history))
      (let loop ((env env)
                 (history history)
                 (current-session-id session-id))
        (let* ((raw-msg (get-message channel))
               (msg (match raw-msg
                      (('eval task)
                       (if (string-prefix? "/" task)
                           (or (parse-slash-command task) raw-msg)
                           raw-msg))
                      (_ raw-msg))))
          (match msg
            ('eof
             (gaia-log (format #f "[SERVER] Client disconnected (session: ~a)." current-session-id))
             (close-port client-socket))
            ('interrupt
             ;; Just reset interrupted flag and loop
             (let ((core-mod (resolve-module '(gaia core) #:ensure #f)))
               (when core-mod
                 (module-set! core-mod '*interrupted* #f)))
             (loop env history current-session-id))
            (('eval task)
             (gaia-log (format #f "[SERVER] Received EVAL request: ~a" task))
             (catch #t
               (lambda ()
                 (let* ((res-pair (rlm-loop current-session-id task 0 history env #:event-handler event-sink #:permission-handler permission-sink))
                        (answer (car res-pair))
                        (updated-history (cdr res-pair)))
                   (gaia-log (format #f "[SERVER] EVAL completed. Saving session ~a." current-session-id))
                   (save-session current-session-id updated-history)
                   (with-output-to-file ".last_session" (lambda () (display current-session-id)))
                   (loop env updated-history current-session-id)))
               (lambda (key . args)
                 (let ((err-msg (format #f "Engine Error (~a): ~a" key args)))
                   (gaia-log (format #f "[SERVER] EVAL error: ~a" err-msg))
                   (send-event client-socket `(error ,err-msg))
                   (loop env history current-session-id)))))
            (('repl code)
             (gaia-log (format #f "[SERVER] Received REPL code execution request."))
             (catch #t
               (lambda ()
                 (let* ((res (rlm-eval! env code #:permission-handler permission-sink))
                        (res-str (format #f "~a" res))
                        (updated-history (append history
                                                 (list `(("role" . "assistant") 
                                                         ("content" . ,(string-append "```repl\n" code "\n```")))
                                                       `(("role" . "user")
                                                         ("content" . ,(string-append "Result:\n" res-str)))))))
                   (gaia-log (format #f "[SERVER] REPL success. Result: ~a" res-str))
                   (save-session current-session-id updated-history)
                   (send-event client-socket `(repl-result ,res-str))
                   (loop env updated-history current-session-id)))
               (lambda (key . args)
                 (let ((err-msg (format #f "REPL Error (~a): ~a" key args)))
                   (gaia-log (format #f "[SERVER] REPL error: ~a" err-msg))
                   (send-event client-socket `(error ,err-msg))
                   (loop env history current-session-id)))))
            (('env)
             (gaia-log "[SERVER] Client requested current environment variables.")
             (let ((bindings (rlm-env-user-bindings env)))
               (send-event client-socket `(env-list ,bindings))
               (loop env history current-session-id)))
            (('clear)
             (gaia-log (format #f "[SERVER] Clearing session ~a environment and history." current-session-id))
             (save-session current-session-id '())
             (send-event client-socket '(info "Environment and history cleared."))
             (loop (make-rlm-env current-session-id event-sink permission-sink) '() current-session-id))
            (('get-model)
             (send-event client-socket `(model-info ,(get-config 'model)))
             (loop env history current-session-id))
            (('set-model new-model)
             (gaia-log (format #f "[SERVER] Hot-swapping model to: ~a" new-model))
             (set-config! 'model new-model)
             (send-event client-socket `(info ,(string-append "Model switched to: " new-model)))
             (loop env history current-session-id))
            (('list-models)
             (let ((models '("gemma4:e2b" "gpt-4o" "claude-3.5-sonnet" "ollama/llama3" "local/ministral")))
               (send-event client-socket `(models-list ,models))
               (loop env history current-session-id)))
            (('get-thinking)
             (let ((thinking (if (get-config 'thinking) "on" "off")))
               (send-event client-socket `(thinking-info ,thinking))
               (loop env history current-session-id)))
            (('set-thinking state)
             (gaia-log (format #f "[SERVER] Set thinking mode to: ~a" state))
             (let ((state-bool (if (string=? state "on") #t #f)))
               (set-config! 'thinking state-bool)
               (send-event client-socket `(info ,(string-append "Thinking mode set to: " state)))
               (loop env history current-session-id)))
            (('ask query)
             (gaia-log (format #f "[SERVER] Received direct ASK request: ~a" query))
             (catch #t
               (lambda ()
                 (let* ((response (chat-with-llm current-session-id query
                                                 (get-config 'model)
                                                 "You are a helpful Guile Scheme expert."
                                                 #:history history
                                                 #:stream-callback event-sink))
                        (payload (assoc-ref response "payload"))
                        (content (if payload (assoc-ref payload "content") "Error: No payload")))
                   (send-event client-socket `(final ,content))
                   (let ((new-history (append history
                                             (list `(("role" . "user") ("content" . ,query))
                                                   `(("role" . "assistant") ("content" . ,content))))))
                     (save-session current-session-id new-history)
                     (loop env new-history current-session-id))))
               (lambda (key . args)
                 (let ((err-msg (format #f "Ask Error (~a): ~a" key args)))
                   (gaia-log (format #f "[SERVER] ASK error: ~a" err-msg))
                   (send-event client-socket `(error ,err-msg))
                   (loop env history current-session-id)))))
            (('session new-id)
             (if (string-null? new-id)
                 (begin
                   (send-event client-socket `(info ,(string-append "Current session ID: " current-session-id)))
                   (loop env history current-session-id))
                 (begin
                   (gaia-log (format #f "[SERVER] Swapping session to: ~a" new-id))
                   (catch #t
                     (lambda ()
                       (let* ((new-history (load-session new-id))
                              (new-env (make-rlm-env new-id event-sink permission-sink)))
                         (with-output-to-file ".last_session" (lambda () (display new-id)))
                         (replay-history new-env new-history)
                         (send-event client-socket `(info ,(string-append "Session switched to: " new-id)))
                         (loop new-env new-history new-id)))
                     (lambda (key . args)
                       (let ((err-msg (format #f "Session Error (~a): ~a" key args)))
                         (gaia-log (format #f "[SERVER] Session swap error: ~a" err-msg))
                         (send-event client-socket `(error ,err-msg))
                         (loop env history current-session-id)))))))
            (('list-sessions)
             (let ((sessions (if (file-exists? "sessions")
                                 (let ((files (scandir "sessions")))
                                   (map (lambda (f) (substring f 0 (- (string-length f) 5)))
                                        (filter (lambda (f) (string-suffix? ".json" f))
                                                files)))
                                 '())))
               (send-event client-socket `(session-list ,sessions))
               (loop env history current-session-id)))
            (('get-history)
             (send-event client-socket `(history-list ,(clean-history history)))
             (loop env history current-session-id))
            (other 
             (gaia-log (format #f "[SERVER] Unknown request command: ~s. Terminating socket." other))
             (close-port client-socket))))))))

(define (start-server path)
  (load-config)
  (gaia-log (format #f "[SERVER] Listening on UNIX socket: ~a" path))
  ;; Ignore SIGPIPE here to avoid hang at top level
  (sigaction SIGPIPE SIG_IGN)
  (with-output-to-file "/tmp/gaia.pid" (lambda () (display (getpid))))
  (when (file-exists? path) (delete-file path))
  (let ((server-socket (socket AF_UNIX SOCK_STREAM 0))
        (addr (make-socket-address AF_UNIX path)))
    (bind server-socket addr)
    (listen server-socket 128)
    (set-nonblocking! server-socket)
    (run-fibers
     (lambda ()
       (let loop ()
         (match (accept server-socket (logior SOCK_NONBLOCK SOCK_CLOEXEC))
           ((client-socket . client-addr)
            (gaia-log "[SERVER] Client connection accepted.")
            (set-nonblocking! client-socket)
            (spawn-fiber (lambda () (handle-client client-socket)))
            (loop)))))
     #:drain? #t)))
