(define-module (gaia llm-client)
  #:use-module (web client)
  #:use-module (web response)
  #:use-module (web uri)
  #:use-module (rnrs bytevectors)
  #:use-module (ice-9 receive)
  #:use-module (ice-9 optargs)
  #:use-module (gaia utils)
  #:use-module (gaia config)
  #:export (chat-with-llm get-models))

(define* (chat-with-llm session-id input model system-prompt #:key (think #f) (history '()))
  (let* ((host (get-config 'llm-url))
         (url (string-append host "/v1/chat/completions"))
         (messages-list (append (list `(("role" . "system") ("content" . ,system-prompt)))
                                history
                                (list `(("role" . "user") ("content" . ,input)))))
         (body (scm->json `(("model" . ,model)
                            ("messages" . ,(list->vector messages-list))
                            ("think" . ,think)
                            ("stream" . #f))))
         (headers '((content-type . (application/json)))))
    (receive (response-header response-body)
        (http-post url #:body body #:headers headers)
      (let* ((body-str (if (string? response-body) response-body (utf8->string response-body)))
             (json-response (catch #t
                                   (lambda () (json->scm body-str))
                                   (lambda (key . args)
                                     `(("error" . ,body-str))))))
        ;; OpenAI format translation to GAIA expected format
        (let ((choices (assoc-ref json-response "choices")))
          (if (and choices (> (vector-length choices) 0))
              (let* ((first-choice (vector-ref choices 0))
                     (message (assoc-ref first-choice "message"))
                     (content (if message (assoc-ref message "content") #f))
                     (reasoning (if message (assoc-ref message "reasoning_content") #f)))
                (if content
                    `(("payload" . (("content" . ,content)
                                    ("reasoning" . ,(or reasoning "")))))
                    json-response))
              json-response))))))

(define (get-models)
  "Fetches the list of available models from OpenAI compatible server."
  (let* ((host (get-config 'llm-url))
         (url (string-append host "/v1/models")))
    (receive (response-header response-body)
        (http-get url)
      (let* ((body-str (if (string? response-body) response-body (utf8->string response-body)))
             (json-response (catch #t
                                   (lambda () (json->scm body-str))
                                   (lambda (key . args)
                                     `(("error" . ,body-str))))))
        (let ((data (assoc-ref json-response "data")))
          (if (vector? data)
              (map (lambda (m) (assoc-ref m "id")) (vector->list data))
              '()))))))
