(define-module (gaia rai-client)
  #:use-module (web client)
  #:use-module (web response)
  #:use-module (web uri)
  #:use-module (rnrs bytevectors)
  #:use-module (ice-9 receive)
  #:use-module (gaia utils)
  #:use-module (gaia config)
  #:export (chat-with-rai create-agent))

(define (create-agent name model system-prompt)
  (let* ((host (get-config 'rai-url))
         (backend (get-config 'backend))
         (framework (get-config 'framework))
         (url (string-append host "/api/v1/agents/" name))
         (body (scm->json `(("model" . ,model)
                            ("system" . ,system-prompt)
                            ("backend" . ,backend)
                            ("framework" . ,framework))))
         (headers '((content-type . (application/json)))))
    (http-post url #:body body #:headers headers)))

(define (chat-with-rai session-id input model system-prompt)
  (let* ((host (get-config 'rai-url))
         (backend (get-config 'backend))
         (framework (get-config 'framework))
         (url (string-append host "/api/v1/run"))
         (body (scm->json `(("chain_input" . ,input)
                            ("session_id" . ,session-id)
                            ("chain_configs" . ,(vector `(("model" . ,model)
                                                          ("system" . ,system-prompt)
                                                          ("backend" . ,backend) 
                                                          ("framework" . ,framework)))))))
         (headers '((content-type . (application/json)))))
    (receive (response-header response-body)
        (http-post url #:body body #:headers headers)
      (let ((json-response (json->scm (utf8->string response-body))))
        json-response))))
