(define-module (gaia rai-client)
  #:use-module (web client)
  #:use-module (web response)
  #:use-module (web uri)
  #:use-module (rnrs bytevectors)
  #:use-module (ice-9 receive)
  #:use-module (gaia utils)
  #:use-module (gaia config)
  #:export (chat-with-rai create-agent get-models))

(define (create-agent name model system-prompt)
  (let* ((host (get-config 'rai-url))
         (backend (get-config 'backend))
         (framework (get-config 'framework))
         (url (string-append host "/api/v1/agents/" name))
         (body (scm->json `(("model" . ,model)
                            ("system" . ,system-prompt)
                            ("backend" . ,backend)
                            ("framework" . ,framework))))
         (headers '((content-type . (application/json)))))
    (http-post url #:body body #:headers headers)))

(define (chat-with-rai session-id input model system-prompt)
  (let* ((host (get-config 'rai-url))
         (backend (get-config 'backend))
         (framework (get-config 'framework))
         (url (string-append host "/api/v1/run"))
         (body (scm->json `(("chain_input" . ,input)
                            ("session_id" . ,session-id)
                            ("chain_configs" . ,(vector `(("model" . ,model)
                                                          ("system" . ,system-prompt)
                                                          ("backend" . ,backend) 
                                                          ("framework" . ,framework)))))))
         (headers '((content-type . (application/json)))))
    (receive (response-header response-body)
        (http-post url #:body body #:headers headers)
      (let* ((body-str (if (string? response-body) response-body (utf8->string response-body)))
             (json-response (catch #t
                                   (lambda () (json->scm body-str))
                                   (lambda (key . args)
                                     `(("error" . ,body-str))))))
        json-response))))

(define (get-models)
  "Fetches the list of available models and adapters from RAI server."
  (let* ((host (get-config 'rai-url))
         (backend (get-config 'backend))
         (url (string-append host "/api/v1/models?backend=" backend)))
    (receive (response-header response-body)
        (http-get url)
      (let* ((body-str (if (string? response-body) response-body (utf8->string response-body)))
             (json-response (catch #t
                                   (lambda () (json->scm body-str))
                                   (lambda (key . args)
                                     `(("error" . ,body-str))))))
        (or (assoc-ref json-response "models") '())))))
